[package]
name = "chesslibrary"
version = "0.1.0"
edition = "2024"

[dependencies]
arrayvec = "0.7.6"
once_cell = "1.21.3" ##For atomic node counting
pyo3 = "0.25.1"

[profile.dev]

[lib]
name = "chesslibrary"
crate-type = ["cdylib", "rlib"]
